[package]
name = "turbosync-cli"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[[bin]]
name = "tsync"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
reqwest.workspace = true
serde.workspace = true
tokio.workspace = true
turbosync-agent = { path = "../turbosync-agent" }
turbosync-core = { path = "../turbosync-core" }
turbosync-storage = { path = "../turbosync-storage" }
tracing.workspace = true
tracing-subscriber.workspace = true

[dev-dependencies]
clap.workspace = true
tempfile.workspace = true
