[package]
name = "turbosync-sync"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
blake3.workspace = true
turbosync-core = { path = "../turbosync-core" }
walkdir.workspace = true

[dev-dependencies]
tempfile.workspace = true
