[package]
name = "turbosync-storage"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
sqlx.workspace = true
turbosync-core = { path = "../turbosync-core" }
uuid.workspace = true

[dev-dependencies]
tempfile.workspace = true
tokio.workspace = true
