[package]
name = "turbosync-agent"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[[bin]]
name = "turbosync-agent"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
axum.workspace = true
clap.workspace = true
serde.workspace = true
sqlx.workspace = true
tokio.workspace = true
turbosync-core = { path = "../turbosync-core" }
turbosync-storage = { path = "../turbosync-storage" }
tracing.workspace = true
tracing-subscriber.workspace = true
